// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Licorera_Corchos.web.Data;

#nullable disable

namespace Proyecto_Licorera_Corchos.web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241009180735_CreateEntidadesTable")]
    partial class CreateEntidadesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Accounting", b =>
                {
                    b.Property<int>("Id_A")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_A"));

                    b.Property<string>("Contrasena_A")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_HModificaciones_A")
                        .HasColumnType("int");

                    b.Property<int>("ModificacionesId_HModificaciones")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_A")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_A");

                    b.HasIndex("ModificacionesId_HModificaciones");

                    b.ToTable("Accounting");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Ausuarios", b =>
                {
                    b.Property<int>("Id_AU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_AU"));

                    b.Property<int>("AccountingId_A")
                        .HasColumnType("int");

                    b.Property<int>("Id_A")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_AU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_AU");

                    b.HasIndex("AccountingId_A");

                    b.ToTable("Ausuarios");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Clientes", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Modificaciones", b =>
                {
                    b.Property<int>("Id_HModificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_HModificaciones"));

                    b.Property<string>("Nombre_H")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_HModificaciones");

                    b.ToTable("Modificaciones");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Pedido", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pedido"));

                    b.Property<int?>("Contacto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Pedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Precio_Pedido")
                        .HasColumnType("money");

                    b.HasKey("Id_Pedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Permisos", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Permiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Productos", b =>
                {
                    b.Property<int>("Id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Producto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuarios"));

                    b.Property<string>("Contrasenna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<int>("PermisosId_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuarios");

                    b.HasIndex("PermisosId_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Ventas", b =>
                {
                    b.Property<int>("Id_Ventas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ventas"));

                    b.Property<DateTime>("Fecha_Ventas")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("int");

                    b.Property<float>("Total_Ventas")
                        .HasColumnType("real");

                    b.HasKey("Id_Ventas");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Accounting", b =>
                {
                    b.HasOne("Proyecto_Licorera_Corchos.web.Data.Entities.Modificaciones", "Modificaciones")
                        .WithMany()
                        .HasForeignKey("ModificacionesId_HModificaciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modificaciones");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Ausuarios", b =>
                {
                    b.HasOne("Proyecto_Licorera_Corchos.web.Data.Entities.Accounting", "Accounting")
                        .WithMany()
                        .HasForeignKey("AccountingId_A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounting");
                });

            modelBuilder.Entity("Proyecto_Licorera_Corchos.web.Data.Entities.Usuarios", b =>
                {
                    b.HasOne("Proyecto_Licorera_Corchos.web.Data.Entities.Permisos", "Permisos")
                        .WithMany()
                        .HasForeignKey("PermisosId_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
